name: Flutter CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: "3.19.6"
      - run: flutter --version

      - name: Install dependencies
        run: flutter pub get
      
      - name: Set up Android SDK
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Install Android SDK
        run: sdkmanager "platform-tools" "platforms;android-30" "build-tools;30.0.3" "system-images;android-30;google_apis;x86"

      - name: Create AVD
        run: avdmanager create avd -n test -k "system-images;android-30;google_apis;x86" --device "pixel"

      - name: Start emulator
        run: |
          nohup emulator -avd test -no-audio -no-window -gpu swiftshader_indirect &
          adb wait-for-device
          adb shell input keyevent 82

      - name: Verify emulator is running
        run: adb devices

      - name: Run end-to-end tests
        run: flutter drive --driver=test_driver/integration_test.dart --target=test/e2e/calculator_e2e_test.dart

