name: Flutter CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: "3.19.6"
      - run: flutter --version

      - name: Install dependencies
        run: flutter pub get

      - name: Run end-to-end tests
        run: flutter drive --driver=test_driver/integration_test_driver.dart --target=test/e2e/calculator_e2e_test.dart

